version: "3.9"
services:
  api:
    platform: linux/amd64
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    env_file: ./api/.env
  web:
    platform: linux/amd64
    build:
      context: ./web
      dockerfile: Dockerfile.web
    # ports:
    #   # - "8443:443"
    #   - 8080:9876
