version: "3.9"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    env_file: ./api/.env
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.web
    ports:
      - "8443:443"
      - "8080:80"
